stages:
  - deploy

pages:
  stage: deploy
  image: rust:latest
  before_script:
    - mkdir -p 'public'
  script:
    - cargo install --debug ssgen
    - ssgen --enable-shell --debug --input ./ --output ./public
  artifacts:
    paths:
      - public
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
